stages:
  - build
  - deploy

deploy:
  stage: deploy
  script:
    - mkdir up
    - mv index.html src up/
    - apk update && apk add --no-cache sshpass openssh
    - sshpass -V
    - export SSHPASS=$USER_PASS
    - sshpass -e scp -o stricthostkeychecking=no up/ ivar@scp.domeneshop.no:/www/
  only:
    - master
