deploy:
  image: alpine
  script:
    - set -e
    - apk update && apk add --no-cache sshpass openssh
    - export SSHPASS=$USER_PASS
    - sshpass -e scp -o stricthostkeychecking=no -r index.html ivar@scp.domeneshop.no:/www/index.html
    - sshpass -e scp -o stricthostkeychecking=no -r src/ ivar@scp.domeneshop.no:/www/src/
  only:
    - master
